//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonNgonTaiNha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAOVIPHAM
    {
        public int idBaoCao { get; set; }
        public Nullable<int> idNguoiGui { get; set; }
        public Nullable<int> idBaiDang { get; set; }
        public Nullable<int> idNguoiDuyet { get; set; }
        public Nullable<int> idTinhTrang { get; set; }
        public string noiDung { get; set; }
        public Nullable<System.DateTime> ngayGui { get; set; }
    
        public virtual BAIDANG BAIDANG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG1 { get; set; }
        public virtual TINHTRANG TINHTRANG { get; set; }
    }
}
