//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonNgonTaiNha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINHLUAN
    {
        public int idBinhLuan { get; set; }
        public Nullable<int> idNguoiBL { get; set; }
        public Nullable<int> idBaiDang { get; set; }
        public string noiDung { get; set; }
        public Nullable<System.DateTime> ngayBinhLuan { get; set; }
    
        public virtual BAIDANG BAIDANG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
