//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonNgonTaiNha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETCONGTHUC
    {
        public int idCongThuc { get; set; }
        public int idNguyenLieu { get; set; }
        public int idCachLam { get; set; }
    
        public virtual CACHLAM CACHLAM { get; set; }
        public virtual CONGTHUC CONGTHUC { get; set; }
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
    }
}
