//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonNgonTaiNha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGTHUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONGTHUC()
        {
            this.CHITIETCONGTHUCs = new HashSet<CHITIETCONGTHUC>();
            this.DANHGIAs = new HashSet<DANHGIA>();
            this.DONHANGs = new HashSet<DONHANG>();
        }
    
        public int idCongThuc { get; set; }
        public string tenMonAn { get; set; }
        public string thoiGianNau { get; set; }
        public Nullable<int> soXu { get; set; }
        public string video { get; set; }
        public Nullable<int> idNguoiDang { get; set; }
        public Nullable<int> idNguoiDuyet { get; set; }
        public Nullable<int> idTinhTrang { get; set; }
        public Nullable<int> idDanhMuc { get; set; }
        public Nullable<int> idBaiDang { get; set; }
    
        public virtual BAIDANG BAIDANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETCONGTHUC> CHITIETCONGTHUCs { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG1 { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual TINHTRANG TINHTRANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
    }
}
