//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonNgonTaiNha.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonNgonTaiNhaEntities : DbContext
    {
        public MonNgonTaiNhaEntities()
            : base("name=MonNgonTaiNhaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAIDANG> BAIDANGs { get; set; }
        public virtual DbSet<BAIVIET> BAIVIETs { get; set; }
        public virtual DbSet<BAOCAOVIPHAM> BAOCAOVIPHAMs { get; set; }
        public virtual DbSet<BINHLUAN> BINHLUANs { get; set; }
        public virtual DbSet<CACHLAM> CACHLAMs { get; set; }
        public virtual DbSet<CHITIETCONGTHUC> CHITIETCONGTHUCs { get; set; }
        public virtual DbSet<CHUNGCHI> CHUNGCHIs { get; set; }
        public virtual DbSet<CONGTHUC> CONGTHUCs { get; set; }
        public virtual DbSet<DANHGIA> DANHGIAs { get; set; }
        public virtual DbSet<DANHMUC> DANHMUCs { get; set; }
        public virtual DbSet<DONHANG> DONHANGs { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual DbSet<NGUYENLIEU> NGUYENLIEUx { get; set; }
        public virtual DbSet<QUYENTRUYCAP> QUYENTRUYCAPs { get; set; }
        public virtual DbSet<TAIKHOANNGANHANG> TAIKHOANNGANHANGs { get; set; }
        public virtual DbSet<TINHTRANG> TINHTRANGs { get; set; }
    }
}
